---
include:
  - board: cornix_left
    snippet: studio-rpc-usb-uart
    artifact-name: cornix_left

  - board: cornix_right
    artifact-name: cornix_right

  - board: cornix_right
    shield: settings_reset
    artifact-name: cornix_right_reset
